version: '3.7'
services:    
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./storage/pg/data:/var/lib/postgresql/data
      - ./storage/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: rts
      POSTGRES_DB: rts
      POSTGRES_PASSWORD: rts

  mongo:
      image: mongo:3.2
      restart: unless-stopped
      volumes:
       - ./storage/mongo/data/db:/data/db
       - ./storage/mongo/data/dump:/dump
      command: mongod --smallfiles --oplogSize 128 --replSet rs0
      labels:
        - "traefik.enable=false"
  
  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./storage/rocketchat/data/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"